### ISSUE TITLE
Npm install throws "@kadira/storybook' is not in the npm registry."

### ISSUE THREAD

**Issue by digitalmaster** [kadira-samples/react-storybook-demo#3]
I get this error when trying to run npm install.

![image](https://cloud.githubusercontent.com/assets/1279335/14218131/2a9a7d4a-f807-11e5-9778-85008c0744d3.png)

**Comment by arunoda** [comment]
That's weird. Are you using the official NPM registry? I heard that scoped packages are not available in some third party NPM mirrors.

**Comment by jskopek** [comment]
I'm a relative beginner to Node, but I fixed a similar issue by updating to NPM v3.8.5. I was using an ancient version of NPM prior to the update, so I doubt a jump from v3.7.1 to v3.8.5 would solve the issue. Still, might be worth trying if you're stuck

**Comment by digitalmaster** [comment]
Seems like it's a known issue.. gonna close this one and link to main issue: https://github.com/kadirahq/react-storybook/issues/15
