### ISSUE TITLE
static file can't be loaded

### ISSUE THREAD

**Issue by azl397985856** [kadira-samples/react-storybook-demo#7]
i need to load  jd.png just by typing that  <Image src="../../assets/jd.png"/>
and i  got a 404 just by http://localhost:9001/asset/jd.png .
in other words, npm run storybook start the static server, but this server dont support static files

**Comment by arunoda** [comment]
Check this: https://github.com/kadirahq/react-storybook/blob/master/docs/api.md#static-directory

**Comment by azl397985856** [comment]
thx
