### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Luketep** [kadira-samples/react-storybook-demo#8]
My setup (versions cannot be changed due to other deps)
`node version: v4.2.3`
`npm version: 1.4.12`
`git version: 2.6.4`

What did I try to execute
`npm i --save-dev @kadira/storybook`

That was the result
`npm WARN package.json react-test@0.0.1 No description`
`npm WARN package.json react-test@0.0.1 No repository field.`
`npm WARN package.json react-test@0.0.1 No README data`
`npm ERR! git clone git@github.com:kadira/storybook Cloning into bare repository '/Users/intern/.npm/_git-remotes/git-github-com-kadira-storybook-0a08009a'...`
`npm ERR! git clone git@github.com:kadira/storybook Permission denied (publickey).`
`npm ERR! git clone git@github.com:kadira/storybook fatal: Could not read from remote repository.`
`npm ERR! git clone git@github.com:kadira/storybook`
`npm ERR! git clone git@github.com:kadira/storybook Please make sure you have the correct access rights`
`npm ERR! git clone git@github.com:kadira/storybook and the repository exists.`
`npm ERR! addLocal Could not install kadira/storybook`
`npm ERR! Error: ENOENT: no such file or directory, stat 'kadira/storybook'`
`npm ERR!     at Error (native)`
`npm ERR! If you need help, you may report this *entire* log,`
`npm ERR! including the npm and node versions, at:`
`npm ERR!     <http://github.com/npm/npm/issues>`
`npm ERR! System Darwin 14.5.0`
`npm ERR! command "/usr/local/Cellar/node4-lts/4.2.3/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "@kadira/storybook"`
`npm ERR! cwd /Users/intern/projects/react-test`
`npm ERR! node -v v4.2.3`
`npm ERR! npm -v 1.4.12`
`npm ERR! path kadira/storybook`
`npm ERR! syscall stat`
`npm ERR! code ENOENT`
`npm ERR! errno -2`
`npm ERR!`
`npm ERR! Additional logging details can be found in:`
`npm ERR!     /Users/intern/projects/react-test/npm-debug.log`
`npm ERR! not ok code 0`

**Comment by arunoda** [comment]
We haven't tested on NPM 1.x and it may won't work.  Try to use NPM 3

**Comment by Luketep** [comment]
Due to other dependencies I cannot change the npm version. If it does not work on 1.x I am afraid I can't use it.

**Comment by arunoda** [comment]
It's not possible to this to work on NPM 1.x. So, give it a try when you can use NPM 3.
